export const INCOME_CREATE_REQUEST = 'INCOME_CREATE_REQUEST';
export const INCOME_CREATE_SUCCESS = 'INCOME_CREATE_SUCCESS';
export const INCOME_CREATE_FAIL = 'INCOME_CREATE_FAIL';

export const INCOME_UPDATE_REQUEST = 'INCOME_UPDATE_REQUEST';
export const INCOME_UPDATE_SUCCESS = 'INCOME_UPDATE_SUCCESS';
export const INCOME_UPDATE_FAIL = 'INCOME_UPDATE_FAIL';

export const INCOME_DELETE_REQUEST = 'INCOME_DELETE_REQUEST';
export const INCOME_DELETE_SUCCESS = 'INCOME_DELETE_SUCCESS';
export const INCOME_DELETE_FAIL = 'INCOME_DELETE_FAIL';

export const BUDGET_CREATE_REQUEST = 'BUDGET_CREATE_REQUEST';
export const BUDGET_CREATE_SUCCESS = 'BUDGET_CREATE_SUCCESS';
export const BUDGET_CREATE_FAIL = 'BUDGET_CREATE_FAIL';
export const BUDGET_CREATE_RESET = 'BUDGET_CREATE_RESET';



export const BUDGET_DELETE_REQUEST = 'BUDGET_DELETE_REQUEST';
export const BUDGET_DELETE_SUCCESS = 'BUDGET_DELETE_SUCCESS';
export const BUDGET_DELETE_FAIL = 'BUDGET_DELETE_FAIL';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';

export const BUDGET_DETAIL_REQUEST = 'BUDGET_DETAIL_REQUEST';
export const BUDGET_DETAIL_SUCCESS = 'BUDGET_DETAIL_SUCCESS';
export const BUDGET_DETAIL_FAIL = 'BUDGET_DETAIL_FAIL';

export const BUDGET_UPDATE_REQUEST = 'BUDGET_UPDATE_REQUEST';
export const BUDGET_UPDATE_SUCCESS = 'BUDGET_UPDATE_SUCCESS';
export const BUDGET_UPDATE_FAIL = 'BUDGET_UPDATE_FAIL';

export const INCOME_DETAIL_REQUEST = 'INCOME_DETAIL_REQUEST';
export const INCOME_DETAIL_SUCCESS = 'INCOME_DETAIL_SUCCESS';
export const INCOME_DETAIL_FAIL = 'INCOME_DETAIL_FAIL';


export const SAVINGS_UPDATE_REQUEST = 'SAVINGS_UPDATE_REQUEST';
export const SAVINGS_UPDATE_SUCCESS = 'SAVINGS_UPDATE_SUCCESS';
export const SAVINGS_UPDATE_FAIL = 'SAVINGS_UPDATE_FAIL';

export const USER_SAVINGS_DETAIL_REQUEST = 'USER_SAVINGS_DETAIL_REQUEST';
export const USER_SAVINGS_DETAIL_SUCCESS = 'USER_SAVINGS_DETAIL_SUCCESS';
export const USER_SAVINGS_DETAIL_FAIL = 'USER_SAVINGS_DETAIL_FAIL';

export const SAVINGS_DELETE_REQUEST = 'SAVINGS_DELETE_REQUEST';
export const SAVINGS_DELETE_SUCCESS = 'SAVINGS_DELETE_SUCCESS';
export const SAVINGS_DELETE_FAIL = 'SAVINGS_DELETE_FAIL';





export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'



export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL'



export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST'
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS'
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL'




export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST'
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS'
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL'

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'
export const POST_CREATE_RESET = 'POST_CREATE_RESET'

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST'
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS'
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL'
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET'



export const POST_CREATE_COMMENT_REQUEST = 'POST_CREATE_COMMENT_REQUEST'
export const POST_CREATE_COMMENT_SUCCESS = 'POST_CREATE_COMMENT_SUCCESS'
export const POST_CREATE_COMMENT_FAIL = 'POST_CREATE_COMMENT_FAIL'
export const POST_CREATE_COMMENT_RESET = 'POST_CREATE_COMMENT_RESET'





export const LIKE_CREATE_REQUEST = 'LIKE_CREATE_REQUEST'
export const LIKE_CREATE_SUCCESS = 'LIKE_CREATE_SUCCESS'
export const LIKE_CREATE_FAIL = 'LIKE_CREATE_FAIL' 





